version: '3.8'

services:
  scrapper:
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    ports:
      - 8081:8081
    networks:
      - app-network

  bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      - scrapper
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
