version: '3.8'

services:

  updates-db:
    image: postgres:14.17
    container_name: updates-db
    restart: always
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - updates-db
    env_file:
      - .env
    command:
      - --searchPath=/changelog
      - --changelog-file=/changelog/master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://updates-db:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    volumes:
      - ./migrations:/changelog
    networks:
      - app-network

  scrapper:
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://updates-db:5432/${POSTGRES_DB} #FROM .env file
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER} #FROM .env file
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD} #FROM .env file
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_PROFILES_ACTIVE: docker
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    depends_on:
      - updates-db
    ports:
      - 8082:8082
    networks:
      - app-network

  bot:
    env_file:
      - .env

    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      - updates-db
      - scrapper

    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
