version: '3.8'

services:

  updates-db:
    image: postgres:14.17
    container_name: updates-db
    restart: always
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network


  scrapper:
    env_file:
      - .env

    build:
      context: .
      dockerfile: scrapper/Dockerfile
    depends_on:
      - updates-db
    ports:
      - 8082:8082
    networks:
      - app-network

  bot:
    env_file:
      - .env

    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      updates-db:
        condition: service_started
      scrapper:
        condition: service_started
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
