app:
  telegram-token: ${TELEGRAM_TOKEN}
url:
  links: "http://scrapper:8082/links"
  tg-chats: "http://scrapper:8082/tg-chat"
spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8082

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
